
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    Connection conn =null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public AddStudent() throws ClassNotFoundException {
        super(" AddStudent");
        initComponents();
        conn = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stdAddress = new javax.swing.JTextField();
        stdName = new javax.swing.JTextField();
        stdGrade = new javax.swing.JTextField();
        stdAge = new javax.swing.JTextField();
        stdgender = new javax.swing.JComboBox<>();
        stdphone = new javax.swing.JTextField();
        stdFatherName = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\aaaaaaaaa\\wp1838784.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Student Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 10, 275, 61);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(29, 130, 80, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Grade");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(29, 257, 58, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(29, 194, 93, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Age");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(29, 323, 30, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(29, 388, 56, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Guardian");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(29, 472, 70, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Contact No.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(29, 552, 93, 22);

        stdAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(stdAddress);
        stdAddress.setBounds(148, 190, 260, 31);

        stdName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(stdName);
        stdName.setBounds(148, 126, 260, 31);

        stdGrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(stdGrade);
        stdGrade.setBounds(148, 257, 260, 31);

        stdAge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(stdAge);
        stdAge.setBounds(148, 319, 260, 31);

        stdgender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stdgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        jPanel1.add(stdgender);
        stdgender.setBounds(148, 381, 260, 37);

        stdphone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(stdphone);
        stdphone.setBounds(148, 548, 260, 31);

        stdFatherName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(stdFatherName);
        stdFatherName.setBounds(148, 472, 260, 31);

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(290, 635, 102, 36);

        submit1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submit1.setText("SUBMIT");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        jPanel1.add(submit1);
        submit1.setBounds(102, 635, 102, 36);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\aaaaaaaaa\\edit.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 550, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
         // TODO add your handling code here:
         try{
             stmt = conn.createStatement();
             String name = stdName.getText();
             String address = stdAddress.getText();
              int grade = Integer.parseInt(stdGrade.getText());
             int age = Integer.parseInt(stdAge.getText());
             String gender = (String) stdgender.getSelectedItem();
             String guardian = stdFatherName.getText();
             int contact = Integer.parseInt(stdphone.getText());
             
             String sql = "INSERT INTO STUDENT(name, address, grade, age, gender, guardian, contact) VALUES('"+name+"', '"+address+"', '"+grade+"', '"+age+"', '"+gender+"', '"+guardian+"', '"+contact+"' )";
             
                  stmt.executeUpdate(sql);
                  JOptionPane.showMessageDialog(null,"added data succsessfully");
                  
         } catch (Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_submit1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
                      setVisible(false);
                     Home object = new Home();
                     object.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField stdAddress;
    private javax.swing.JTextField stdAge;
    private javax.swing.JTextField stdFatherName;
    private javax.swing.JTextField stdGrade;
    private javax.swing.JTextField stdName;
    private javax.swing.JComboBox<String> stdgender;
    private javax.swing.JTextField stdphone;
    private javax.swing.JButton submit1;
    // End of variables declaration//GEN-END:variables
}
